<?php

namespace CodeDistortion\Adapt\Exceptions;

use GuzzleHttp\Exception\BadResponseException;
use GuzzleHttp\Exception\ConnectException;
use Psr\Http\Message\ResponseInterface;
use Throwable;

/**
 * Exceptions generated when building a database remotely.
 */
class AdaptRemoteBuildException extends AdaptException
{
    /** @var string|null The message to show in the log - so the regular exception message can be different. */
    private $messageForLog;

    /** @var string|null The url used to build a database remotely. */
    private $remoteBuildUrl;

    /** @var ResponseInterface|null The error message generated by the remote server. */
    private $response;



    /**
     * The request to build a database remotely failed.
     *
     * @param string $driver The driver that isn't allowed to be built remotely.
     * @return self
     */
    public static function databaseTypeCannotBeBuiltRemotely($driver): self
    {
        return new self("$driver databases cannot be built remotely");
    }

    /**
     * The request to build a database remotely failed.
     *
     * @param string $remoteBuildUrl The "remote-build" url.
     * @return self
     */
    public static function remoteBuildUrlInvalid($remoteBuildUrl): self
    {
        return new self("The remote build url \"$remoteBuildUrl\" is invalid");
    }

    /**
     * The request to build a database remotely failed.
     *
     * @param string                 $connection        The connection the database was being built for.
     * @param string                 $remoteBuildUrl    The url used to build a database remotely.
     * @param ResponseInterface|null $response          The response to the build http request.
     * @param Throwable|null         $originalException The originally thrown exception.
     * @return static
     */
    public static function remoteBuildFailed(
        $connection,
        $remoteBuildUrl,
        $response,
        $originalException = null
    ): self {

        $message = "The remote database for connection \"$connection\" could not be built - see log for more details";
        $messageForLog = "The remote database for connection \"$connection\" could not be built";

        $exception = $originalException
            ? new self($message, 0, $originalException)
            : new self($message);

        $exception->messageForLog = $messageForLog;
        $exception->remoteBuildUrl = $remoteBuildUrl;
        $exception->response = $response;

        return $exception;
    }





    /**
     * Get the http response status.
     *
     * @return string|null
     */
    private function buildMessage()
    {
        $responseMessage = $this->interpretRemoteMessage();

        $e = $this->getPrevious();
        if ($e instanceof ConnectException) {
            return "Could not connect to $this->remoteBuildUrl";
        } elseif ($e instanceof BadResponseException) {
            return $responseMessage
                ? "Remote error message: \"{$responseMessage}\""
                : null;
        } elseif (!is_null($responseMessage)) {
            return "Remote error message: \"{$responseMessage}\"";
        }
        return "Unknown error";
    }

    /**
     * Get the http response status.
     *
     * @return string|null
     */
    private function interpretRemoteMessage()
    {
        if (!$this->response) {
            return null;
        }

        // don't bother with a message if it's a 404 - it's pretty self-explanatory
        if ($this->response->getStatusCode() == 404) {
            return null;
        }

        $responseMessage = $this->response->getBody()->getContents();
        return mb_strlen($responseMessage) > 200
            ? mb_substr($responseMessage, 0, 200) . '…'
            : $responseMessage;
    }



    /**
     * Generate the exception title to log.
     *
     * @return string
     */
    public function generateTitleForLog(): string
    {
        return 'The Remote Build Failed';
    }

    /**
     * Build the lines to log.
     *
     * @return string[]
     */
    public function generateLinesForLog(): array
    {
        // don't include the url if the connection couldn't be made
        // as the url is included in the message
        $e = $this->getPrevious();
        $statusCode = $this->response ? $this->response->getStatusCode() : null;
        $url = (!$e instanceof ConnectException)
            ? $this->remoteBuildUrl . ($statusCode ? " ($statusCode)" : '')
            : null;

        if (!$this->messageForLog) {
            return array_filter([$this->getMessage()]);
        }

        return array_filter([
            $this->messageForLog,
            $url,
            $this->buildMessage(),
        ]);
    }
}
