<?php

namespace CodeDistortion\Adapt\Exceptions;

/**
 * Exceptions generated by the PropBag class.
 */
class AdaptPropBagDTOException extends AdaptException
{
    /**
     * Return a new instance when a property does not exist.
     *
     * @param string $name The name of the unexpected property.
     * @return self
     */
    public static function propertyDoesNotExist(string $name)
    {
        return new self('Property "' . $name . '" hasn\'t been added');
    }
}
