name: "run-tests"

on:
  push:
    branches: [ "master", "master-*" ]
  pull_request:
    branches: [ "master", "master-*" ]
  schedule:
    - cron: "0 0 * * 0"

jobs:

  all_tests:

    name: "PHP${{ matrix.php }} TB${{ matrix.testbench }} ${{ matrix.os-title }} ${{ matrix.dependency-prefer-title }}"
    runs-on: "${{ matrix.os }}"
    permissions:
      contents: "read"
    strategy:
      fail-fast: false
      matrix:
        # os: [ "ubuntu-latest", "macos-latest", "windows-latest" ]
        os: [ "ubuntu-latest", "macos-latest" ]
        php: [ "8.4", "8.3", "8.2", "8.1", "8.0", "7.4", "7.3", "7.2", "7.1", "7.0" ]
        testbench: [ "^10.0", "^9.0", "^8.0", "^7.0", "^6.0", "^5.0", "^4.0", "^3.8.1", "3.7.*", "3.6.*", "3.5.*", "3.4.*", "3.3.*", "3.2.*", "3.1.*" ]
        dependency-prefer: [ "prefer-stable", "prefer-lowest" ]
        include:
          - testbench: "^10.0"
            phpunit: "^9.3 | ^10.1 | ^11.0 | ^12.0"
            phpunit-config-file: "phpunit.github-actions.xml.dist"
          - testbench: "^9.0"
            phpunit: "^9.3 | ^10.1 | ^11.0 | ^12.0"
            phpunit-config-file: "phpunit.github-actions.xml.dist"
          - testbench: "^8.0"
            phpunit: "^9.3 | ^10.1 | ^11.0 | ^12.0"
            phpunit-config-file: "phpunit.github-actions.xml.dist"
          - testbench: "^7.0"
            phpunit: "^5.0 | ^6.0 | ^7.0 | ^8.0 | ^9.0"
            phpunit-config-file: "phpunit.github-actions.up-to-9.xml.dist"
          - testbench: "^6.0"
            phpunit: "^5.0 | ^6.0 | ^7.0 | ^8.0 | ^9.0"
            phpunit-config-file: "phpunit.github-actions.up-to-9.xml.dist"
          - testbench: "^5.0"
            phpunit: "^5.0 | ^6.0 | ^7.0 | ^8.0 | ^9.0"
            phpunit-config-file: "phpunit.github-actions.up-to-9.xml.dist"
          - testbench: "^4.0"
            phpunit: "^5.0 | ^6.0 | ^7.0 | ^8.0 | ^9.0"
            phpunit-config-file: "phpunit.github-actions.up-to-9.xml.dist"
          - testbench: "^3.8.1"
            phpunit: "^5.0 | ^6.0 | ^7.0 | ^8.0 | ^9.0"
            phpunit-config-file: "phpunit.github-actions.up-to-9.xml.dist"
          - testbench: "3.7.*"
            phpunit: "^5.0 | ^6.0 | ^7.0 | ^8.0 | ^9.0"
            phpunit-config-file: "phpunit.github-actions.up-to-9.xml.dist"
          - testbench: "3.6.*"
            phpunit: "^5.0 | ^6.0 | ^7.0 | ^8.0 | ^9.0"
            phpunit-config-file: "phpunit.github-actions.up-to-9.xml.dist"
          - testbench: "3.5.*"
            phpunit: "^5.0 | ^6.0 | ^7.0 | ^8.0 | ^9.0"
            phpunit-config-file: "phpunit.github-actions.up-to-9.xml.dist"
          - testbench: "3.4.*"
            phpunit: "^5.0"
            phpunit-config-file: "phpunit.github-actions.up-to-9.xml.dist"
          - testbench: "3.3.*"
            phpunit: "~4.8 | ~5.0"
            phpunit-config-file: "phpunit.github-actions.up-to-9.xml.dist"
          - testbench: "3.2.*"
            phpunit: "~4.8 | ~5.0"
            phpunit-config-file: "phpunit.github-actions.up-to-9.xml.dist"
          - testbench: "3.1.*"
            phpunit: "~4.8 | ~5.0"
            phpunit-config-file: "phpunit.github-actions.up-to-9.xml.dist"

          - os: "ubuntu-latest"
            os-title: "ubuntu"
          - os: "macos-latest"
            os-title: "macos"
          # - os: "windows-latest"
          #   os-title: "win"

          - dependency-prefer: "prefer-stable"
            dependency-prefer-title: "stable"
          - dependency-prefer: "prefer-lowest"
            dependency-prefer-title: "lowest"
        exclude:
          - testbench: "^10.0"
            php: "8.1"
          - testbench: "^10.0"
            php: "8.0"
          - testbench: "^10.0"
            php: "7.4"
          - testbench: "^10.0"
            php: "7.3"
          - testbench: "^10.0"
            php: "7.2"
          - testbench: "^10.0"
            php: "7.1"
          - testbench: "^10.0"
            php: "7.0"

          - testbench: "^9.0"
            php: "8.1"
          - testbench: "^9.0"
            php: "8.0"
          - testbench: "^9.0"
            php: "7.4"
          - testbench: "^9.0"
            php: "7.3"
          - testbench: "^9.0"
            php: "7.2"
          - testbench: "^9.0"
            php: "7.1"
          - testbench: "^9.0"
            php: "7.0"

          - testbench: "^8.0"
            php: "8.0"
          - testbench: "^8.0"
            php: "7.4"
          - testbench: "^8.0"
            php: "7.3"
          - testbench: "^8.0"
            php: "7.2"
          - testbench: "^8.0"
            php: "7.1"
          - testbench: "^8.0"
            php: "7.0"

          - testbench: "^7.0"
            php: "7.4"
          - testbench: "^7.0"
            php: "7.3"
          - testbench: "^7.0"
            php: "7.2"
          - testbench: "^7.0"
            php: "7.1"
          - testbench: "^7.0"
            php: "7.0"

          - testbench: "^6.0"
            php: "8.4"
          - testbench: "^6.0"
            php: "8.3"
            dependency-prefer: "prefer-lowest"
          - testbench: "^6.0"
            php: "8.2"
            dependency-prefer: "prefer-lowest"
          - testbench: "^6.0"
            php: "8.1"
            dependency-prefer: "prefer-lowest"
          - testbench: "^6.0"
            php: "7.2"
          - testbench: "^6.0"
            php: "7.1"
          - testbench: "^6.0"
            php: "7.0"

          - testbench: "^5.0"
            php: "8.4"
          - testbench: "^5.0"
            php: "8.3"
          - testbench: "^5.0"
            php: "8.2"
          - testbench: "^5.0"
            php: "8.1"
          - testbench: "^5.0"
            php: "7.1"
          - testbench: "^5.0"
            php: "7.0"

          - testbench: "^4.0"
            php: "8.4"
          - testbench: "^4.0"
            php: "8.3"
          - testbench: "^4.0"
            php: "8.2"
          - testbench: "^4.0"
            php: "8.1"
          - testbench: "^4.0"
            php: "7.1"
          - testbench: "^4.0"
            php: "7.1"
          - testbench: "^4.0"
            php: "7.0"

          - testbench: "^3.8.1"
            php: "8.4"
          - testbench: "^3.8.1"
            php: "8.3"
          - testbench: "^3.8.1"
            php: "8.2"
          - testbench: "^3.8.1"
            php: "8.1"
          - testbench: "^3.8.1"
            php: "8.0"
          - testbench: "^3.8.1"
            php: "7.1"
          - testbench: "^3.8.1"
            php: "7.0"

          - testbench: "3.7.*"
            php: "8.4"
          - testbench: "3.7.*"
            php: "8.3"
          - testbench: "3.7.*"
            php: "8.2"
          - testbench: "3.7.*"
            php: "8.1"
          - testbench: "3.7.*"
            php: "8.0"
          - testbench: "3.7.*"
            php: "7.0"

          - testbench: "3.6.*"
            php: "8.4"
          - testbench: "3.6.*"
            php: "8.3"
          - testbench: "3.6.*"
            php: "8.2"
          - testbench: "3.6.*"
            php: "8.1"
          - testbench: "3.6.*"
            php: "8.0"
          - testbench: "3.6.*"
            php: "7.0"

          - testbench: "3.5.*"
            php: "8.4"
          - testbench: "3.5.*"
            php: "8.3"
          - testbench: "3.5.*"
            php: "8.2"
          - testbench: "3.5.*"
            php: "8.1"
          - testbench: "3.5.*"
            php: "8.0"

          - testbench: "3.4.*"
            php: "8.4"
          - testbench: "3.4.*"
            php: "8.3"
          - testbench: "3.4.*"
            php: "8.2"
          - testbench: "3.4.*"
            php: "8.1"
          - testbench: "3.4.*"
            php: "8.0"

          - testbench: "3.3.*"
            php: "8.4"
          - testbench: "3.3.*"
            php: "8.3"
          - testbench: "3.3.*"
            php: "8.2"
          - testbench: "3.3.*"
            php: "8.1"
          - testbench: "3.3.*"
            php: "8.0"
          - testbench: "3.3.*"
            php: "7.4"

          - testbench: "3.2.*"
            php: "8.4"
          - testbench: "3.2.*"
            php: "8.3"
          - testbench: "3.2.*"
            php: "8.2"
          - testbench: "3.2.*"
            php: "8.1"
          - testbench: "3.2.*"
            php: "8.0"
          - testbench: "3.2.*"
            php: "7.4"

          - testbench: "3.1.*"
            php: "8.4"
          - testbench: "3.1.*"
            php: "8.3"
          - testbench: "3.1.*"
            php: "8.2"
          - testbench: "3.1.*"
            php: "8.1"
          - testbench: "3.1.*"
            php: "8.0"
          - testbench: "3.1.*"
            php: "7.4"
          - testbench: "3.1.*"
            dependency-prefer: "prefer-lowest"

          - php: "7.4"
            dependency-prefer: "prefer-lowest"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"

      - name: "Setup PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php }}"
          extensions: "fileinfo, mbstring, pdo_mysql, pdo_sqlite" # league/flysystem on Windows requires fileinfo
          ini-values: "error_reporting=E_ALL"
          coverage: "none"
        env:
          COMPOSER_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Validate composer.json and composer.lock"
        run: "composer validate --strict"

      # find composer's cache directory - so we know which directory to cache in the next step
      - name: "Find composer's cache directory"
        id: "composer-cache"
        shell: "bash" # make sure this step works on Windows - see https://github.com/actions/runner/issues/2224#issuecomment-1289533957
        run: |
          echo "composer_cache_dir=$(composer config cache-files-dir)">> "$GITHUB_OUTPUT"

      - name: "Cache composer's cache directory"
        uses: "actions/cache@v4"
        with:
          path: "${{ steps.composer-cache.outputs.composer_cache_dir }}"
          key: "[${{ matrix.os }}][php-${{ matrix.php }}][testbench-${{ matrix.testbench }}][${{ matrix.dependency-prefer }}][composer.json-${{ hashFiles('composer.json') }}]"

      - name: "Install dependencies"
        uses: "nick-fields/retry@v3"
        with:
          timeout_minutes: 5
          max_attempts: 5
          shell: "bash" # make sure "^" characters are interpreted properly on Windows (e.g. in "^5.0")
          command: |
            composer remove "infection/infection" --dev --no-interaction --no-update
            composer require "orchestra/testbench:${{ matrix.testbench }}" --dev --no-interaction --no-update
            composer remove "phpstan/phpstan" --dev --no-interaction --no-update
            composer remove "phpstan/phpstan-strict-rules" --dev --no-interaction --no-update
            composer require "phpunit/phpunit:${{ matrix.phpunit }}" --dev --no-interaction --no-update
            composer remove "squizlabs/php_codesniffer" --dev --no-interaction --no-update
            composer update --${{ matrix.dependency-prefer }} --prefer-dist --no-interaction --optimize-autoloader --no-progress

      - name: "Execute tests"
        run: vendor/bin/phpunit "--configuration=${{ matrix.phpunit-config-file }}" --no-coverage --stop-on-error --stop-on-failure
